mwl.mysql_payments:
  - user_hash_key
  - project_id
  - closed_at
  - operation_id
  - status
  - sum
  - sum_usd 
  - operation_id
mwl.mysql_users:
  - user_hash_key
  - user_id
  - project_id
  - fake
  - registration_date
  - email
  - gender
reference.project:
  - projec_id
  - name
